### ISSUE TITLE
How to config openwrt if I expand SDRAM to 32MB?

### ISSUE THREAD

**Issue by aafaba** [JiapengLi/OpenWrt-HiLink-HLK-RM04#1]
Sorry I am new to openwrt, my board has 32MB memory/4M flash, how/where to change the config?

**Comment by JiapengLi** [comment]
Is your board HLK-RM04 module? If so see the OpenWrt wiki. There is no need to modify the hardware. But you need to edit the hlk-rm04.dts file to comment the **memory** node.
http://wiki.openwrt.org/toh/hilink/hlk-rm04#memory.configuration

May be you can describe your problem in details, so that i can help more.

**Comment by aafaba** [comment]
My board is not HLK-RM04, it shipped with 32M SDRAM. I want to run openwrt on it.

**Comment by JiapengLi** [comment]
I don't think that i can help this. You may see the OpenWrt support
hardware list to see if your board is supported.

2013/9/21 aafaba notifications@github.com
